// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	v1 "github.com/AFK068/bot/internal/api/openapi/bot/v1"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// PostUpdates provides a mock function with given fields: ctx, update
func (_m *Service) PostUpdates(ctx context.Context, update v1.LinkUpdate) error {
	ret := _m.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for PostUpdates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.LinkUpdate) error); ok {
		r0 = rf(ctx, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_PostUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostUpdates'
type Service_PostUpdates_Call struct {
	*mock.Call
}

// PostUpdates is a helper method to define mock.On call
//   - ctx context.Context
//   - update v1.LinkUpdate
func (_e *Service_Expecter) PostUpdates(ctx interface{}, update interface{}) *Service_PostUpdates_Call {
	return &Service_PostUpdates_Call{Call: _e.mock.On("PostUpdates", ctx, update)}
}

func (_c *Service_PostUpdates_Call) Run(run func(ctx context.Context, update v1.LinkUpdate)) *Service_PostUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.LinkUpdate))
	})
	return _c
}

func (_c *Service_PostUpdates_Call) Return(_a0 error) *Service_PostUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_PostUpdates_Call) RunAndReturn(run func(context.Context, v1.LinkUpdate) error) *Service_PostUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
