with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  "github.com/AFK068/bot/internal/domain":
    all: true
  "github.com/AFK068/bot/internal/middleware":
    all: true
  "github.com/AFK068/bot/internal/application/bot":
    all: true
  "github.com/AFK068/bot/pkg/client/github":
    all: true
  "github.com/AFK068/bot/pkg/client/stackoverflow":
    all: true
  "github.com/AFK068/bot/internal/infrastructure/clients/bot":
    all: true
  "github.com/AFK068/bot/internal/infrastructure/clients/scrapper":
    all: true