// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/AFK068/bot/pkg/client/github"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// GitHubRepoFetcher is an autogenerated mock type for the GitHubRepoFetcher type
type GitHubRepoFetcher struct {
	mock.Mock
}

type GitHubRepoFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *GitHubRepoFetcher) EXPECT() *GitHubRepoFetcher_Expecter {
	return &GitHubRepoFetcher_Expecter{mock: &_m.Mock}
}

// GetActivity provides a mock function with given fields: ctx, repository, lastCheckTime
func (_m *GitHubRepoFetcher) GetActivity(ctx context.Context, repository *github.Repository, lastCheckTime time.Time) ([]*github.Activity, error) {
	ret := _m.Called(ctx, repository, lastCheckTime)

	if len(ret) == 0 {
		panic("no return value specified for GetActivity")
	}

	var r0 []*github.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *github.Repository, time.Time) ([]*github.Activity, error)); ok {
		return rf(ctx, repository, lastCheckTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *github.Repository, time.Time) []*github.Activity); ok {
		r0 = rf(ctx, repository, lastCheckTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *github.Repository, time.Time) error); ok {
		r1 = rf(ctx, repository, lastCheckTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GitHubRepoFetcher_GetActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivity'
type GitHubRepoFetcher_GetActivity_Call struct {
	*mock.Call
}

// GetActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - repository *github.Repository
//   - lastCheckTime time.Time
func (_e *GitHubRepoFetcher_Expecter) GetActivity(ctx interface{}, repository interface{}, lastCheckTime interface{}) *GitHubRepoFetcher_GetActivity_Call {
	return &GitHubRepoFetcher_GetActivity_Call{Call: _e.mock.On("GetActivity", ctx, repository, lastCheckTime)}
}

func (_c *GitHubRepoFetcher_GetActivity_Call) Run(run func(ctx context.Context, repository *github.Repository, lastCheckTime time.Time)) *GitHubRepoFetcher_GetActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*github.Repository), args[2].(time.Time))
	})
	return _c
}

func (_c *GitHubRepoFetcher_GetActivity_Call) Return(_a0 []*github.Activity, _a1 error) *GitHubRepoFetcher_GetActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GitHubRepoFetcher_GetActivity_Call) RunAndReturn(run func(context.Context, *github.Repository, time.Time) ([]*github.Activity, error)) *GitHubRepoFetcher_GetActivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepo provides a mock function with given fields: ctx, questionURL
func (_m *GitHubRepoFetcher) GetRepo(ctx context.Context, questionURL string) (*github.Repository, error) {
	ret := _m.Called(ctx, questionURL)

	if len(ret) == 0 {
		panic("no return value specified for GetRepo")
	}

	var r0 *github.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*github.Repository, error)); ok {
		return rf(ctx, questionURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *github.Repository); ok {
		r0 = rf(ctx, questionURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, questionURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GitHubRepoFetcher_GetRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepo'
type GitHubRepoFetcher_GetRepo_Call struct {
	*mock.Call
}

// GetRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - questionURL string
func (_e *GitHubRepoFetcher_Expecter) GetRepo(ctx interface{}, questionURL interface{}) *GitHubRepoFetcher_GetRepo_Call {
	return &GitHubRepoFetcher_GetRepo_Call{Call: _e.mock.On("GetRepo", ctx, questionURL)}
}

func (_c *GitHubRepoFetcher_GetRepo_Call) Run(run func(ctx context.Context, questionURL string)) *GitHubRepoFetcher_GetRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GitHubRepoFetcher_GetRepo_Call) Return(_a0 *github.Repository, _a1 error) *GitHubRepoFetcher_GetRepo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GitHubRepoFetcher_GetRepo_Call) RunAndReturn(run func(context.Context, string) (*github.Repository, error)) *GitHubRepoFetcher_GetRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewGitHubRepoFetcher creates a new instance of GitHubRepoFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitHubRepoFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitHubRepoFetcher {
	mock := &GitHubRepoFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
