storage:
    type: sql
    host: "postgresql"
    port: "5432"
    database_name: "scrapper"
    user: "postgres"
    password: ${POSTGRES_PASSWORD}
migrations:
    migrations_path: ../../../../../migrations/changesets
    migrations_table_name: migrations

