storage:
    type: sql
    host: "localhost"
    port: "5432"
    database_name: "scrapper"
    user: "postgres"
    password: "password"
migrations:
    migrations_path: "../../../../../migrations/changesets"
    migrations_table_name: "migrations"
