openapi: 3.0.0
info:
  title: Bot API
  version: 1.0.0
  contact:
    name: Alexander Biryukov
    url: https://github.com
paths:
  /updates:
    post:
      summary: Отправить обновление
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkUpdate'
        required: true
      responses:
        '200':
          description: Обновление обработано
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  schemas:
    ApiErrorResponse:
      type: object
      properties:
        description:
          type: string
        code:
          type: string
        exceptionName:
          type: string
        exceptionMessage:
          type: string
        stacktrace:
          type: array
          items:
            type: string
    LinkUpdate:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
          format: uri
        description:
          type: string
        сreatedAt:
          type: string
          format: date-time
        UserName:
          type: string
        Type:
          type: string
          enum:
            - stackoverflow_comment
            - stackoverflow_answer
            - stackoverflow_question
            - github_repository
            - github_issue
            - github_pull_request
            
        tgChatIds:
          type: array
          items:
            type: integer
            format: int64